Added ep42
omoiyarifm/omoiyarifm.github.io pull request #37
Opened 2019-02-15 17:57 UTC by miuranobuaki

# 追加したもの
- [x] shownoteファイル
- [x] audioファイル

# レビューしてほしいもの
- shownoteのリンクが正しいか
- shownoteに不要なものが入ってないか
- shownoteに誤字脱字がないか

2019-02-16 01:21 UTC, ykmc09 requested changes
スマホからざっと！リンク確認、アフィリンクはまた追ってやりまーす

2019-02-16 01:21 UTC, ykmc09 commented on _posts/2019-02-18-42.md
> +- MicroSoftとインテルがエコシステムを作れた理由
Microsoft (s小文字)

2019-02-16 01:21 UTC, ykmc09 commented on _posts/2019-02-18-42.md
> +- Windows2000の開発
Windows 2000 (スペースあり

2019-02-16 01:21 UTC, ykmc09 commented on _posts/2019-02-18-42.md
> +- MicroSoftのトップダウンの凄さ
同じく社名

2019-02-16 01:21 UTC, ykmc09 commented on _posts/2019-02-18-42.md
> +- [不機嫌な長男・長女 無責任な末っ子たち 「きょうだい型」性格分析&コミュニケーション](https://www.amazon.co.jp/dp/4799319620)
後でアフィリンク生成しまーす！

2019-02-16 01:21 UTC, ykmc09 commented on _posts/2019-02-18-42.md
> +- 迷路を描くエンジニア
https://twitter.com/hasegawa_fusao/status/1064506854900883456?s=19
これだった

2019-02-16 11:47 UTC, ykmc09 requested changes
アフィリンク追加しましたー

2019-02-16 11:47 UTC, ykmc09 commented on _posts/2019-02-18-42.md
> +- [闘うプログラマー](https://www.amazon.co.jp/dp/B00GSHI04M)
https://amzn.to/2Ie1ber

2019-02-16 11:47 UTC, ykmc09 commented on _posts/2019-02-18-42.md
> +- [不機嫌な長男・長女 無責任な末っ子たち 「きょうだい型」性格分析&コミュニケーション](https://www.amazon.co.jp/dp/4799319620)
https://amzn.to/2Ij6w4g

2019-02-16 11:47 UTC, ykmc09 commented on _posts/2019-02-18-42.md
> +- [ウェブ進化論 本当の大変化はこれから始まる](https://www.amazon.co.jp/dp/4480062858)
https://amzn.to/2IfAeY8

2019-02-18 09:49 UTC, miuranobuaki commented on _posts/2019-02-18-42.md
> +- MicroSoftとインテルがエコシステムを作れた理由
Done!

2019-02-18 09:49 UTC, miuranobuaki commented on _posts/2019-02-18-42.md
> +- Windows2000の開発
Done!

2019-02-18 09:49 UTC, miuranobuaki commented on _posts/2019-02-18-42.md
> +- MicroSoftのトップダウンの凄さ
Done!

2019-02-18 09:50 UTC, miuranobuaki commented on _posts/2019-02-18-42.md
> +- [不機嫌な長男・長女 無責任な末っ子たち 「きょうだい型」性格分析&コミュニケーション](https://www.amazon.co.jp/dp/4799319620)
下で対応しますー

2019-02-18 09:50 UTC, miuranobuaki commented on _posts/2019-02-18-42.md
> +- 迷路を描くエンジニア
リンク追加しました！

2019-02-18 09:50 UTC, miuranobuaki commented on _posts/2019-02-18-42.md
> +- [闘うプログラマー](https://www.amazon.co.jp/dp/B00GSHI04M)
Done!

2019-02-18 09:51 UTC, miuranobuaki commented on _posts/2019-02-18-42.md
> +- [ウェブ進化論 本当の大変化はこれから始まる](https://www.amazon.co.jp/dp/4480062858)
Done!

2019-02-18 09:52 UTC, miuranobuaki commented
一通り対応しましたー！

2019-02-18 10:17 UTC, miuranobuaki commented
merge

2019-02-18 10:17 UTC, merged