Added ep.44
omoiyarifm/omoiyarifm.github.io pull request #40
Opened 2019-02-28 08:12 UTC by miuranobuaki

# やったこと
- [x] 画像追加
- [x] _config.yamlの修正
- [x] 音源追加
- [x] postの追加

# レビューしてほしいこと
- ローカルの確認のために日付を `2019-02-28` にしているけど、大丈夫か
  - 2019-03-01にする？
- postの内容

2019-03-01 02:11 UTC, ykmc09 requested changes

2019-03-01 02:11 UTC, ykmc09 commented on _posts/2019-03-01-44.md
> +- [Fukabori.fm #fukabori](https://fukabori.fm/)
この下にこれもぜひ！
`- [実践「最高のアジャイルチーム」を作る方法 - ログミーTech](https://logmi.jp/tech/articles/320513)`

2019-03-01 02:11 UTC, ykmc09 commented on _posts/2019-03-01-44.md
> +title: "#44 Passive skills obtained from Scrum training"
`The passive skills obtained in Scrum training` か `Passive skills that can be obtained in Scrum training` なきもするけど、自信はないｗ

2019-03-01 02:11 UTC, ykmc09 commented on _posts/2019-03-01-44.md
> +NTT コミュニケーションズ、Fukabori.fm パーソナリティの @iwashi86 さんとともに>
`>` はゴミ？

2019-03-01 02:13 UTC, ykmc09 commented
イワシさんに、ハッシュタグ紹介してもらってるところ、ジングル付きの差し替えられたら差し替えたい！ｗ
急にジングル入る的な

2019-03-01 02:15 UTC, ykmc09 commented on _posts/2019-03-01-44.md
> +title: "#44 Passive skills obtained from Scrum training"
日本語に逃げると `#44 パッシブスキルを獲得する` とか？

2019-03-01 02:17 UTC, miuranobuaki commented on _posts/2019-03-01-44.md
> +title: "#44 Passive skills obtained from Scrum training"
日本語に逃げますかねw

2019-03-01 02:17 UTC, miuranobuaki commented on _posts/2019-03-01-44.md
> +NTT コミュニケーションズ、Fukabori.fm パーソナリティの @iwashi86 さんとともに>
完全にゴミですね

2019-03-01 02:18 UTC, miuranobuaki commented
音源の修正となると今日の夜まで対応できないんですけど良いですかね？

2019-03-01 03:18 UTC, ykmc09 commented
> 音源の修正となると今日の夜まで対応できないんですけど良いですかね？

いっそ月曜日に繰り越すか・・・！
ぜひ今回作ってくれたジングル使いたい・・・！

2019-03-02 06:26 UTC, miuranobuaki commented on _posts/2019-03-01-44.md
> +- [Fukabori.fm #fukabori](https://fukabori.fm/)
Done!

2019-03-02 06:26 UTC, miuranobuaki commented on _posts/2019-03-01-44.md
> +title: "#44 Passive skills obtained from Scrum training"
Done!

2019-03-02 06:27 UTC, miuranobuaki commented on _posts/2019-03-01-44.md
> +NTT コミュニケーションズ、Fukabori.fm パーソナリティの @iwashi86 さんとともに>
Done

2019-03-03 13:34 UTC, merged